# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

display_url: https://driveclean-teste.netlify.app

logo_url: https://driveclean.pt/assets/images/favicon.png

locale: 'pt'

media_library:
  folder_support: true

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Portfolio" # Used in the UI, ie.: "New Post"
    label_singular: "publicação"
    description: "Aqui aparecem as publicações que estao no portfolio, pode adicionar uma nova clicando no botão -Novo(a) publicação-. Tambem pode ordenar por titulo/data de publicação ou agrupar por Ano/Tags"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:dsc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      size: 'half'
    summary_fields:
      - title
      - date
      - tags
    sortable_fields:
      fields:
        - title
        - date
      default:
        field: date
        direction: Descending
    view_groups:
      - label: Year
        field: date
        pattern: '\d{4}'
      - label: Tags
        field: tags
    preview_path: "/portfolio/{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titulo", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descrição Meta", name: "meta_description", widget: "string"}
      - name: tags
        label: Tags
        widget: relation
        collection: tags
        search_fields: [title, description]
        value_field: title
        multiple: true
      - {label: "Data da Publicação", name: "date", widget: "datetime", format: "yyyy-MM-dd hh:mm:ss"}
      - {label: "Paragrafo de introdução", name: "intro_paragraph", widget: "string"}
      - {label: "Conteudo", name: "body", widget: "markdown"}
      - {label: Imagem de capa, name: image, widget: image}
    #teste tags
  - name: tags
    label: Tags
    description: "Aqui pode adicionar/alterar as Tags que aparecem para selecionar nas publicações"
    folder: "_tags"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "tag"}
      - {name: title, label: Nome}
      - {name: description, label: descrição, widget: text}
    #CABEÇALHO 
  - name: 'site_settings'
    label: 'Configurações do site'
    editor:
      preview: false
    files:
    - label: 'Cabeçalho'
      name: 'header'
      file: '_data/header.yml'
      fields:
        - {label: "Contactos", name: "contact", widget: "string"}
        - {label: "Contacto principal", name: "default_contact", widget: "string"}
    - label: 'Rodapé'
      name: 'footer'
      file: '_data/footer.yml'
      fields:
        - {label: "Morada", name: "adress", widget: "string"}
        - {label: "Nº Movel", name: "mobile_number", widget: "string"}
        - {label: "Nº Fixo", name: "office_number", widget: "string"}
        - {label: "Email", name: "email", widget: "string"}
    - label: 'Overview'
      name: 'overview'
      file: '_data/overview.yml'
      fields:
        - {label: "Anos de Experiência", name: "experience", widget: "string"}
        - {label: "Serviços efetuados", name: "services", widget: "string"}
        - {label: "Modelos trabalhados", name: "models", widget: "string"}
        - {label: "Seguidores Instagram", name: "instagram", widget: "string"}
    
