# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

display_url: https://driveclean.pt/

logo_url: https://driveclean.pt/assets/images/favicon.png

locale: 'pt'

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Portfolio" # Used in the UI, ie.: "New Post"
    label_singular: "publicação"
    description: "Entries sortable by Publish Date or title on 'Sort by' button teste"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{date | date('DD-yyyy')}} - {{title}}"
    preview_path: portfolio/{{title}}
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titulo", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descrição Meta", name: "meta_description", widget: "string", required: false}
      - name: tags
        label: Tags
        widget: relation
        collection: tags
        search_fields: [title, description]
        value_field: title
        multiple: true
      - {label: "Data da Publicação", name: "date", widget: "datetime", format: "yyyy-MM-DD HH:mm:ss"}
      - {label: "Paragrafo de introdução", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Conteudo", name: "body", widget: "markdown", required: false}
      - {label: "Categorias", name: "categories", widget: "string", required: false}
      - {label: Imagem de capa, name: image, widget: image}
    #teste tags
  - name: tags
    label: Tags
    folder: "_tags"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "tag"}
      - {name: title, label: Nome}
      - {name: description, label: descrição, widget: text}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
    #CABEÇALHO 
  - name: 'site_settings'
    label: 'Configurações do site'
    editor:
      preview: false
    files:
    - label: 'Cabeçalho'
      name: 'header'
      file: '_data/header.yml'
      fields:
        - {label: "Contactos", name: "contact", widget: "string"}
        - {label: "Contacto principal", name: "default_contact", widget: "string"}
    - label: 'Rodapé'
      name: 'footer'
      file: '_data/footer.yml'
      fields:
        - {label: "Morada", name: "adress", widget: "string"}
        - {label: "Nº Movel", name: "mobile_number", widget: "string"}
        - {label: "Nº Fixo", name: "office_number", widget: "string"}
        - {label: "Email", name: "email", widget: "string"}
    - label: 'Overview'
      name: 'overview'
      file: '_data/overview.yml'
      fields:
        - {label: "Anos de Experiência", name: "experience", widget: "string"}
        - {label: "Serviços efetuados", name: "services", widget: "string"}
        - {label: "Modelos trabalhados", name: "models", widget: "string"}
        - {label: "Seguidores Instagram", name: "instagram", widget: "string"}
    
